### ISSUE TITLE
Ant command problem at 'org.apromore.similaritysearch-portal'

### ISSUE THREAD

**Issue by noalnak** [apromore/ApromoreCore#174]
I am executing the command 'ant start-virgo' and the script stops at: 'org.apromore.similaritysearch-portal'. The complete error message is:

[exec] [2018-04-16 07:20:04.377] start-signalling-9           <DE0010I> Stopping bundle 'org.apromore.similaritysearch-logic' version '1.1.0'. 
     [exec] [2018-04-16 07:20:04.378] start-signalling-9           <DE0011I> Stopped bundle 'org.apromore.similaritysearch-logic' version '1.1.0'. 
     [exec] [2018-04-16 07:20:08.525] service-monitor-thread-1     <KE0100W> Reference '&similarityService' in bundle 'org.apromore.similaritysearch-portal' version '1.1.0' is waiting for service with filter '(objectClass=org.apromore.plugin.similaritysearch.logic.SimilarityService)'. 
     [exec] [2018-04-16 07:21:08.527] service-monitor-thread-1     <KE0100W> Reference '&similarityService' in bundle 'org.apromore.similaritysearch-portal' version '1.1.0' is waiting for service with filter '(objectClass=org.apromore.plugin.similaritysearch.logic.SimilarityService)'. 

Please help. Thanks.

**Comment by alirezaostovar** [comment]
Hi,
Have you browsed "http://localhost:9000" once it stops?

**Comment by noalnak** [comment]
Yes and I was able to go to the Login Page. When I encoded the 'admin/password' credentials, this is the Error I received:

HTTP Status 500 - Could not access HTTP invoker remote service at [http://localhost:9000/manager/remoting/remoteAuth]; nested exception is java.io.StreamCorruptedException: invalid stream header: 3C21444F

**Comment by sabatale** [comment]
Same error here. Apromore's build ended successfully, but ant start-virgo ends with a similar error and the localhost displays a blank page. All services seem to time out - excerpt, here:

```
[2019-10-13 22:41:13.724] INFO  ng DM Context Creation Timer org.eclipse.virgo.nano.core.internal.BundleStartTracker           Handling event 'org.osgi.service.event.Event [topic=org/osgi/service/blueprint/container/FAILURE]' 
[2019-10-13 22:41:13.724] ERROR ng DM Context Creation Timer org.eclipse.virgo.nano.core.internal.BundleStartTracker           Recording application context construction failure 'org.springframework.context.ApplicationContextException: Application context initialization for 'org.apromore.plugin.bpmnminer-portal-plugin' has timed out waiting for (|(objectClass=org.apromore.service.CanoniserService)(objectClass=org.apromore.service.DomainService)(objectClass=org.apromore.service.ProcessService)(objectClass=org.apromore.service.EventLogService)(objectClass=org.apromore.service.UserService)(objectClass=org.apromore.service.helper.UserInterfaceHelper))' for bundle 'org.apromore.plugin.bpmnminer-portal-plugin_1.1.0 [328]' 
[2019-10-13 22:41:13.724] INFO  start-signalling-7           org.eclipse.virgo.nano.core.internal.BundleStartTracker           Driving signal 'org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal@2007dede' 
[2019-10-13 22:41:13.724] ERROR ng DM Context Creation Timer o.e.g.b.extender.internal.activator.ContextLoaderListener         Application context refresh failed (OsgiBundleXmlApplicationContext(bundle=org.apromore.plugin.bpmnminer-portal-plugin, config=osgibundle:/META-INF/spring/*.xml)) org.springframework.context.ApplicationContextException: Application context initialization for 'org.apromore.plugin.bpmnminer-portal-plugin' has timed out waiting for (|(objectClass=org.apromore.service.CanoniserService)(objectClass=org.apromore.service.DomainService)(objectClass=org.apromore.service.ProcessService)(objectClass=org.apromore.service.EventLogService)(objectClass=org.apromore.service.UserService)(objectClass=org.apromore.service.helper.UserInterfaceHelper))
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.timeout(DependencyWaiterApplicationContextExecutor.java:489)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.access$000(DependencyWaiterApplicationContextExecutor.java:54)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$WatchDogTask.run(DependencyWaiterApplicationContextExecutor.java:109)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

[2019-10-13 22:41:13.724] INFO  start-signalling-7           o.e.v.k.i.artifact.internal.bundle.BundleThreadContextManager     Thread context class loader 'KernelBundleClassLoader: [bundle=org.eclipse.gemini.blueprint.extender_1.0.2.RELEASE]' pushed and set to 'KernelBundleClassLoader: [bundle=org.apromore.plugin.bpmnminer-portal-plugin_1.1.0]' 
[2019-10-13 22:41:13.724] INFO  ng DM Context Creation Timer o.s.beans.factory.support.DefaultListableBeanFactory              Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@6f06b65b: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.context.config.internalBeanConfigurerAspect,bimpAnnotationService,bpmnMinerService,canoniserService,domainService,processService,eventLogService,userService,infrequentBehaviourFilter,userInterfaceHelper,plugin,org.eclipse.gemini.blueprint.service.exporter.support.OsgiServiceFactoryBean#0]; root of factory hierarchy 
[2019-10-13 22:41:13.724] ERROR ng DM Context Creation Timer o.e.g.b.e.i.d.startup.DependencyWaiterApplicationContextExecutor  Unable to create application context for [org.apromore.plugin.bpmnminer-portal-plugin], unsatisfied dependencies: Dependency on [(objectClass=org.apromore.service.helper.UserInterfaceHelper)] (from bean [&userInterfaceHelper]), Dependency on [(objectClass=org.apromore.service.ProcessService)] (from bean [&processService]), Dependency on [(objectClass=org.apromore.service.UserService)] (from bean [&userService]), Dependency on [(objectClass=org.apromore.service.CanoniserService)] (from bean [&canoniserService]), Dependency on [(objectClass=org.apromore.service.DomainService)] (from bean [&domainService]), Dependency on [(objectClass=org.apromore.service.EventLogService)] (from bean [&eventLogService]) org.springframework.context.ApplicationContextException: Application context initialization for 'org.apromore.plugin.bpmnminer-portal-plugin' has timed out waiting for (|(objectClass=org.apromore.service.CanoniserService)(objectClass=org.apromore.service.DomainService)(objectClass=org.apromore.service.ProcessService)(objectClass=org.apromore.service.EventLogService)(objectClass=org.apromore.service.UserService)(objectClass=org.apromore.service.helper.UserInterfaceHelper))
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.timeout(DependencyWaiterApplicationContextExecutor.java:489)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.access$000(DependencyWaiterApplicationContextExecutor.java:54)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$WatchDogTask.run(DependencyWaiterApplicationContextExecutor.java:109)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

[2019-10-13 22:41:13.725] ERROR start-signalling-7           org.eclipse.virgo.medic.eventlog.default                         DE0006E Start failed for bundle 'org.apromore.plugin.bpmnminer-portal-plugin' version '1.1.0'. org.springframework.context.ApplicationContextException: Application context initialization for 'org.apromore.plugin.bpmnminer-portal-plugin' has timed out waiting for (|(objectClass=org.apromore.service.CanoniserService)(objectClass=org.apromore.service.DomainService)(objectClass=org.apromore.service.ProcessService)(objectClass=org.apromore.service.EventLogService)(objectClass=org.apromore.service.UserService)(objectClass=org.apromore.service.helper.UserInterfaceHelper))
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.timeout(DependencyWaiterApplicationContextExecutor.java:489)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.access$000(DependencyWaiterApplicationContextExecutor.java:54)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$WatchDogTask.run(DependencyWaiterApplicationContextExecutor.java:109)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

[2019-10-13 22:41:13.725] INFO  start-signalling-7           o.e.v.k.i.artifact.internal.bundle.BundleThreadContextManager     Thread context class loader 'KernelBundleClassLoader: [bundle=org.apromore.plugin.bpmnminer-portal-plugin_1.1.0]' popped and set to 'KernelBundleClassLoader: [bundle=org.eclipse.gemini.blueprint.extender_1.0.2.RELEASE]' 
[2019-10-13 22:41:13.725] INFO  start-signalling-7           o.e.v.k.i.artifact.internal.bundle.BundleThreadContextManager     Thread context class loader 'KernelBundleClassLoader: [bundle=org.eclipse.gemini.blueprint.extender_1.0.2.RELEASE]' pushed and set to 'KernelBundleClassLoader: [bundle=org.apromore.plugin.bpmnminer-portal-plugin_1.1.0]' 
[2019-10-13 22:41:13.725] INFO  start-signalling-7           o.e.v.k.i.artifact.internal.bundle.BundleThreadContextManager     Thread context class loader 'KernelBundleClassLoader: [bundle=org.apromore.plugin.bpmnminer-portal-plugin_1.1.0]' pushed and set to 'KernelBundleClassLoader: [bundle=org.apromore.plugin.bpmnminer-portal-plugin_1.1.0]' 
[2019-10-13 22:41:13.726] INFO  start-signalling-7           org.eclipse.virgo.medic.eventlog.default                         DE0010I Stopping bundle 'org.apromore.plugin.bpmnminer-portal-plugin' version '1.1.0'. 
[2019-10-13 22:41:13.726] INFO  start-signalling-7           org.eclipse.virgo.nano.core.internal.BundleStartTracker           Bundle 'org.apromore.plugin.bpmnminer-portal-plugin_1.1.0 [328]' has stopped. Removing its related tracking state. 
[2019-10-13 22:41:13.726] INFO  start-signalling-7           org.eclipse.virgo.medic.eventlog.default                         DE0011I Stopped bundle 'org.apromore.plugin.bpmnminer-portal-plugin' version '1.1.0'. 
[2019-10-13 22:41:13.726] INFO  start-signalling-7           o.e.v.k.i.artifact.internal.bundle.BundleThreadContextManager     Thread context class loader 'KernelBundleClassLoader: [bundle=org.apromore.plugin.bpmnminer-portal-plugin_1.1.0]' popped and set to 'KernelBundleClassLoader: [bundle=org.apromore.plugin.bpmnminer-portal-plugin_1.1.0]' 
[2019-10-13 22:41:13.726] INFO  start-signalling-7           o.e.v.k.i.artifact.internal.bundle.BundleThreadContextManager     Thread context class loader 'KernelBundleClassLoader: [bundle=org.apromore.plugin.bpmnminer-portal-plugin_1.1.0]' popped and set to 'KernelBundleClassLoader: [bundle=org.eclipse.gemini.blueprint.extender_1.0.2.RELEASE]' 
[2019-10-13 22:41:13.727] INFO  OSGiLogServiceListener@55196 org.osgi.service.log.LogService                                   Bundle org.apromore.plugin.bpmnminer-portal-plugin_1.1.0, BundleEvent STOPPED 

```

I haven't had time to troubleshoot the thing yet, but here are a few errors which get triggered at the beginning:

`[2019-10-13 22:30:21.458] ERROR system-artifacts             org.apache.catalina.mbeans.GlobalResourcesLifecycleListener       No global naming context defined for server `
```
[2019-10-13 22:30:29.607] ERROR fs-watcher                   org.eclipse.virgo.medic.eventlog.default                         DE0700E Cannot find configuration 'git' version range '[0.0.0, oo)' in repository 'ext-usr'. 
[2019-10-13 22:30:29.613] ERROR fs-watcher                   org.eclipse.virgo.medic.eventlog.default                         DE0002E Installation of plan 'org.apromore.manager' version '1.1.0' failed. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Deployment of plan 'org.apromore.manager' version '1.1.0' in scope 'null' failed: configuration 'git' in version range '[0.0.0, oo)' not found
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.operate(PlanResolver.java:116)
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.access$0(PlanResolver.java:92)
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver$1.visit(PlanResolver.java:86)
	at org.eclipse.virgo.util.common.ThreadSafeGraphNode.visitInternal(ThreadSafeGraphNode.java:193)
	at org.eclipse.virgo.util.common.ThreadSafeGraphNode.visit(ThreadSafeGraphNode.java:184)
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.transform(PlanResolver.java:82)
	at org.eclipse.virgo.kernel.install.pipeline.stage.transform.internal.TransformationStage.doProcessGraph(TransformationStage.java:54)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.internal.CompensatingPipeline.doProcessGraph(CompensatingPipeline.java:73)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
	at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:359)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.doInstall(PipelinedApplicationDeployer.java:185)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.install(PipelinedApplicationDeployer.java:140)
	at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.deploy(PipelinedApplicationDeployer.java:253)
	at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deploy(HotDeployerFileSystemListener.java:225)
	at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deployIfNotDeployed(HotDeployerFileSystemListener.java:237)
	at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.onChange(HotDeployerFileSystemListener.java:88)
	at org.eclipse.virgo.util.io.FileSystemChecker.notifyListeners(FileSystemChecker.java:380)
	at org.eclipse.virgo.util.io.FileSystemChecker.check(FileSystemChecker.java:289)
	at org.eclipse.virgo.nano.deployer.hot.WatchTask.run(WatchTask.java:49)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.virgo.nano.deployer.api.core.DeploymentException: configuration 'git' in version range '[0.0.0, oo)' not found
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.obtainInstallArtifactGraph(PlanResolver.java:165)
	at org.eclipse.virgo.kernel.deployer.core.internal.PlanResolver.operate(PlanResolver.java:101)
	... 23 common frames omitted

[2019-10-13 22:30:29.613] INFO  fs-watcher                   o.e.v.k.m.i.deployer.ModelInstallArtifactLifecycleListener        Processing install failed event for configuration 'site' version '0.0.0' 
[2019-10-13 22:30:29.613] ERROR fs-watcher                   org.eclipse.virgo.medic.eventlog.default                         DE0003E Install failed for configuration 'site' version '0.0.0'. 
[2019-10-13 22:30:29.614] INFO  fs-watcher                   o.e.v.k.m.i.deployer.ModelInstallArtifactLifecycleListener        Processing install failed event for plan 'org.apromore.manager' version '1.1.0' 
[2019-10-13 22:30:29.614] ERROR fs-watcher                   org.eclipse.virgo.medic.eventlog.default                         DE0003E Install failed for plan 'org.apromore.manager' version '1.1.0'. 
[2019-10-13 22:30:29.618] INFO  fs-watcher                   System.out                                                        org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Deployment of plan 'org.apromore.manager' version '1.1.0' in scope 'null' failed: configuration 'git' in version range '[0.0.0, oo)' not found 
```

**Comment by verenich** [comment]
Hi @sabatale Fixed and tested on Windows. Please pull the latest code from master and repeat the process.

**Comment by philimon-laf** [comment]
Hi @verenich although we pulled the latest code, we still facing the same problem, that @noalnak  described.
Could you kindly advise.

Thank you in advance
