### ISSUE TITLE
Trying to install Apromore on Ubuntu, ant can't resolve dependencies

### ISSUE THREAD

**Issue by denoide1** [apromore/ApromoreCore#182]
I've installed all the correct versions of the required packets such as maven 3.3.9, ant 1.9.2 and Server JRE

i can build the source code correctly with maven 3.3.9 but when i try to execute "ant start-virgo" 

ant logs show multiple errors regarding missing dependencies

Here's a sample of the error 

```
<HD0002E> Hot deploy failed for file '~metrics-editor-plugin-1.1.war'. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Dependency satisfaction failed
     [exec]     at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:362)
     [exec]     at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.doInstall(PipelinedApplicationDeployer.java:185)
     [exec]     at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.install(PipelinedApplicationDeployer.java:140)
     [exec]     at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.deploy(PipelinedApplicationDeployer.java:253)
     [exec]     at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deploy(HotDeployerFileSystemListener.java:225)
     [exec]     at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.deployIfNotDeployed(HotDeployerFileSystemListener.java:237)
     [exec]     at org.eclipse.virgo.nano.deployer.hot.HotDeploymentFileSystemListener.onChange(HotDeployerFileSystemListener.java:88)
     [exec]     at org.eclipse.virgo.util.io.FileSystemChecker.notifyListeners(FileSystemChecker.java:380)
     [exec]     at org.eclipse.virgo.util.io.FileSystemChecker.check(FileSystemChecker.java:289)
     [exec]     at org.eclipse.virgo.nano.deployer.hot.WatchTask.run(WatchTask.java:49)
     [exec]     at java.lang.Thread.run(Thread.java:748)
     [exec] Caused by: org.eclipse.virgo.kernel.osgi.framework.UnableToSatisfyBundleDependenciesException: Unable to satisfy dependencies of bundle 'org.apromore.plugin.metrics-editor-plugin' at version '1.1.0': Cannot resolve: org.apromore.plugin.metrics-editor-plugin
     [exec]     Resolver report:
     [exec]         An Import-Package could not be resolved. Resolver error data <Import-Package: org.apromore.service.bpmndiagramimporter; version="[1.1.0,2.0.0)">. Caused by missing constraint in bundle <org.apromore.plugin.metrics-editor-plugin_1.1.0>
     [exec]              constraint: <Import-Package: org.apromore.service.bpmndiagramimporter; version="[1.1.0,2.0.0)">
     [exec] 
     [exec]     at org.eclipse.virgo.kernel.install.pipeline.stage.resolve.internal.QuasiResolveStage.process(QuasiResolveStage.java:46)
     [exec]     at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
     [exec]     at org.eclipse.virgo.kernel.install.pipeline.internal.CompensatingPipeline.doProcessGraph(CompensatingPipeline.java:73)
     [exec]     at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
     [exec]     at org.eclipse.virgo.kernel.install.pipeline.internal.StandardPipeline.doProcessGraph(StandardPipeline.java:62)
     [exec]     at org.eclipse.virgo.kernel.install.pipeline.stage.AbstractPipelineStage.process(AbstractPipelineStage.java:41)
     [exec]     at org.eclipse.virgo.kernel.deployer.core.internal.PipelinedApplicationDeployer.driveInstallPipeline(PipelinedApplicationDeployer.java:359)
     [exec]     ... 10 common frames omitted
```

There are plenty of similar logs, how can i fix this problem?

**Comment by denoide1** [comment]
is windows server supported instead?
